In [1]:
import pandas as pd
import requests
from datetime import datetime
import os
from dotenv import load_dotenv

# Making the API call and viewing the json

If you want to search for the city by name and country instead of latitude and longitude, try using the [Geocoding API](https://openweathermap.org/api/geocoding-api).

In [2]:
# Berlin
latitude = 52.520008
longitude = 13.404954

#API_key = userdata.get('openWeatherApi')
load_dotenv()
API_key = os.getenv("openWeatherApi")

# check out the docs for more info on making an api call https://openweathermap.org/forecast5
url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")

response = requests.get(url)
json = response.json()

json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1779915600,
   'main': {'temp': 16.54,
    'feels_like': 15.42,
    'temp_min': 15.01,
    'temp_max': 16.54,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 45,
    'temp_kf': 1.53},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.94, 'deg': 331, 'gust': 6.35},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-27 21:00:00'},
  {'dt': 1779926400,
   'main': {'temp': 14.67,
    'feels_like': 13.76,
    'temp_min': 13.35,
    'temp_max': 14.67,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1019,
    'humidity': 60,
    'temp_kf': 1.32},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 7},
   'wind': {'speed': 2.7, 'deg': 313, 'gust': 5.47},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-28 00:00:00'},
  {'dt': 1779937200,
   'main': {'temp': 10.69,
    'feels_like': 9.93,
    'temp_min': 10.69,
    'temp_max': 10.69,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 81,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 6},
   'wind': {'speed': 2.92, 'deg': 308, 'gust': 5.95},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 03:00:00'},
  {'dt': 1779948000,
   'main': {'temp': 14.42,
    'feels_like': 13.67,
    'temp_min': 14.42,
    'temp_max': 14.42,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 3.03, 'deg': 302, 'gust': 4.23},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 06:00:00'},
  {'dt': 1779958800,
   'main': {'temp': 18.84,
    'feels_like': 17.82,
    'temp_min': 18.84,
    'temp_max': 18.84,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 40,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 24},
   'wind': {'speed': 3.49, 'deg': 299, 'gust': 4.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 09:00:00'},
  {'dt': 1779969600,
   'main': {'temp': 21.63,
    'feels_like': 20.68,
    'temp_min': 21.63,
    'temp_max': 21.63,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 24},
   'wind': {'speed': 3.94, 'deg': 300, 'gust': 4.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 12:00:00'},
  {'dt': 1779980400,
   'main': {'temp': 20.9,
    'feels_like': 19.88,
    'temp_min': 20.9,
    'temp_max': 20.9,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1019,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 21},
   'wind': {'speed': 4.24, 'deg': 301, 'gust': 4.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 15:00:00'},
  {'dt': 1779991200,
   'main': {'temp': 18.41,
    'feels_like': 17.38,
    'temp_min': 18.41,
    'temp_max': 18.41,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1018,
    'humidity': 41,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 17},
   'wind': {'speed': 4.02, 'deg': 296, 'gust': 4.77},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-28 18:00:00'},
  {'dt': 1780002000,
   'main': {'temp': 14.5,
    'feels_like': 13.6,
    'temp_min': 14.5,
    'temp_max': 14.5,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 61,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 10},
   'wind': {'speed': 1.75, 'deg': 359, 'gust': 2.79},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-28 21:00:00'},
  {'dt': 1780012800,
   'main': {'temp': 13.36,
    'feels_like': 12.53,
    'temp_min': 13.36,
    'temp_max': 13.36,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 29},
   'wind': {'speed': 0.6, 'deg': 215, 'gust': 0.75},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-29 00:00:00'},
  {'dt': 1780023600,
   'main': {'temp': 12.06,
    'feels_like': 11.12,
    'temp_min': 12.06,
    'temp_max': 12.06,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 69,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 21},
   'wind': {'speed': 1.46, 'deg': 253, 'gust': 1.58},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 03:00:00'},
  {'dt': 1780034400,
   'main': {'temp': 15.67,
    'feels_like': 14.65,
    'temp_min': 15.67,
    'temp_max': 15.67,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 16},
   'wind': {'speed': 2.14, 'deg': 223, 'gust': 3.25},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 06:00:00'},
  {'dt': 1780045200,
   'main': {'temp': 21.07,
    'feels_like': 20.2,
    'temp_min': 21.07,
    'temp_max': 21.07,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1018,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 14},
   'wind': {'speed': 2.95, 'deg': 248, 'gust': 3.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 09:00:00'},
  {'dt': 1780056000,
   'main': {'temp': 24.8,
    'feels_like': 23.96,
    'temp_min': 24.8,
    'temp_max': 24.8,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1016,
    'humidity': 24,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 10},
   'wind': {'speed': 3.71, 'deg': 285, 'gust': 4.43},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 12:00:00'},
  {'dt': 1780066800,
   'main': {'temp': 25.55,
    'feels_like': 24.84,
    'temp_min': 25.55,
    'temp_max': 25.55,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 1015,
    'humidity': 26,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 6},
   'wind': {'speed': 4.07, 'deg': 294, 'gust': 5.35},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 15:00:00'},
  {'dt': 1780077600,
   'main': {'temp': 22.34,
    'feels_like': 21.78,
    'temp_min': 22.34,
    'temp_max': 22.34,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 44,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 38},
   'wind': {'speed': 2.87, 'deg': 321, 'gust': 5.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-29 18:00:00'},
  {'dt': 1780088400,
   'main': {'temp': 19.37,
    'feels_like': 19.09,
    'temp_min': 19.37,
    'temp_max': 19.37,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1013,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.86, 'deg': 242, 'gust': 4.87},
   'visibility': 10000,
   'pop': 0.51,
   'rain': {'3h': 0.25},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-29 21:00:00'},
  {'dt': 1780099200,
   'main': {'temp': 17.46,
    'feels_like': 17.56,
    'temp_min': 17.46,
    'temp_max': 17.46,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1012,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.75, 'deg': 288, 'gust': 8.79},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.61},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-30 00:00:00'},
  {'dt': 1780110000,
   'main': {'temp': 16.49,
    'feels_like': 16.6,
    'temp_min': 16.49,
    'temp_max': 16.49,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1011,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.32, 'deg': 285, 'gust': 9.32},
   'visibility': 10000,
   'pop': 0.93,
   'rain': {'3h': 0.41},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 03:00:00'},
  {'dt': 1780120800,
   'main': {'temp': 16.97,
    'feels_like': 16.79,
    'temp_min': 16.97,
    'temp_max': 16.97,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1011,
    'humidity': 79,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 86},
   'wind': {'speed': 5.24, 'deg': 304, 'gust': 8.01},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 0.37},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 06:00:00'},
  {'dt': 1780131600,
   'main': {'temp': 20.35,
    'feels_like': 19.72,
    'temp_min': 20.35,
    'temp_max': 20.35,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1011,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 3},
   'wind': {'speed': 5.49, 'deg': 310, 'gust': 7.25},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 09:00:00'},
  {'dt': 1780142400,
   'main': {'temp': 22.93,
    'feels_like': 22.32,
    'temp_min': 22.93,
    'temp_max': 22.93,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1011,
    'humidity': 40,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 5.87, 'deg': 307, 'gust': 7.55},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 12:00:00'},
  {'dt': 1780153200,
   'main': {'temp': 21.42,
    'feels_like': 20.98,
    'temp_min': 21.42,
    'temp_max': 21.42,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1010,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 20},
   'wind': {'speed': 6.23, 'deg': 302, 'gust': 7.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 15:00:00'},
  {'dt': 1780164000,
   'main': {'temp': 19.19,
    'feels_like': 18.78,
    'temp_min': 19.19,
    'temp_max': 19.19,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 57},
   'wind': {'speed': 4.26, 'deg': 308, 'gust': 6.44},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-30 18:00:00'},
  {'dt': 1780174800,
   'main': {'temp': 16.15,
    'feels_like': 16.01,
    'temp_min': 16.15,
    'temp_max': 16.15,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1010,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 75},
   'wind': {'speed': 2.53, 'deg': 317, 'gust': 5.46},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-30 21:00:00'},
  {'dt': 1780185600,
   'main': {'temp': 14.46,
    'feels_like': 14.29,
    'temp_min': 14.46,
    'temp_max': 14.46,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 53},
   'wind': {'speed': 2.23, 'deg': 291, 'gust': 4.74},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-31 00:00:00'},
  {'dt': 1780196400,
   'main': {'temp': 12.94,
    'feels_like': 12.64,
    'temp_min': 12.94,
    'temp_max': 12.94,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 28},
   'wind': {'speed': 2.2, 'deg': 293, 'gust': 4.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 03:00:00'},
  {'dt': 1780207200,
   'main': {'temp': 15.09,
    'feels_like': 14.59,
    'temp_min': 15.09,
    'temp_max': 15.09,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1009,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 61},
   'wind': {'speed': 2.83, 'deg': 283, 'gust': 4.24},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 06:00:00'},
  {'dt': 1780218000,
   'main': {'temp': 20.41,
    'feels_like': 19.73,
    'temp_min': 20.41,
    'temp_max': 20.41,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 47,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 60},
   'wind': {'speed': 2.33, 'deg': 281, 'gust': 2.82},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 09:00:00'},
  {'dt': 1780228800,
   'main': {'temp': 23.6,
    'feels_like': 23.01,
    'temp_min': 23.6,
    'temp_max': 23.6,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 38,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 70},
   'wind': {'speed': 3.21, 'deg': 277, 'gust': 3.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 12:00:00'},
  {'dt': 1780239600,
   'main': {'temp': 24.34,
    'feels_like': 23.8,
    'temp_min': 24.34,
    'temp_max': 24.34,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 61},
   'wind': {'speed': 3.52, 'deg': 307, 'gust': 4.08},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 15:00:00'},
  {'dt': 1780250400,
   'main': {'temp': 20.82,
    'feels_like': 20.29,
    'temp_min': 20.82,
    'temp_max': 20.82,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 51,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 80},
   'wind': {'speed': 2.86, 'deg': 333, 'gust': 4.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-31 18:00:00'},
  {'dt': 1780261200,
   'main': {'temp': 19.02,
    'feels_like': 18.49,
    'temp_min': 19.02,
    'temp_max': 19.02,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.31, 'deg': 320, 'gust': 1.97},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-31 21:00:00'},
  {'dt': 1780272000,
   'main': {'temp': 16.32,
    'feels_like': 15.86,
    'temp_min': 16.32,
    'temp_max': 16.32,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 71,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.25, 'deg': 278, 'gust': 3.59},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-06-01 00:00:00'},
  {'dt': 1780282800,
   'main': {'temp': 14.89,
    'feels_like': 14.6,
    'temp_min': 14.89,
    'temp_max': 14.89,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1004,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.88, 'deg': 261, 'gust': 7.43},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-06-01 03:00:00'},
  {'dt': 1780293600,
   'main': {'temp': 14.43,
    'feels_like': 14.17,
    'temp_min': 14.43,
    'temp_max': 14.43,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.46, 'deg': 282, 'gust': 10.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-06-01 06:00:00'},
  {'dt': 1780304400,
   'main': {'temp': 19.12,
    'feels_like': 18.5,
    'temp_min': 19.12,
    'temp_max': 19.12,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 96},
   'wind': {'speed': 5.21, 'deg': 284, 'gust': 7.3},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-06-01 09:00:00'},
  {'dt': 1780315200,
   'main': {'temp': 22.41,
    'feels_like': 21.72,
    'temp_min': 22.41,
    'temp_max': 22.41,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 85},
   'wind': {'speed': 4.91, 'deg': 274, 'gust': 6.95},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-06-01 12:00:00'},
  {'dt': 1780326000,
   'main': {'temp': 19.15,
    'feels_like': 18.64,
    'temp_min': 19.15,
    'temp_max': 19.15,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 91},

# Exploring the json
Remember, if you want to know more about any of the information in the json, or you're unsure what a key is, check out the [open weather docs](https://openweathermap.org/forecast5).

First, let's look at the keys

In [3]:
json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [4]:
json["cod"]

'200'

In [5]:
json["message"]

0

In [6]:
json["cnt"]

40

In [7]:
json["list"]

[{'dt': 1779915600,
  'main': {'temp': 16.54,
   'feels_like': 15.42,
   'temp_min': 15.01,
   'temp_max': 16.54,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1019,
   'humidity': 45,
   'temp_kf': 1.53},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 4},
  'wind': {'speed': 2.94, 'deg': 331, 'gust': 6.35},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-27 21:00:00'},
 {'dt': 1779926400,
  'main': {'temp': 14.67,
   'feels_like': 13.76,
   'temp_min': 13.35,
   'temp_max': 14.67,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1019,
   'humidity': 60,
   'temp_kf': 1.32},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 7},
  'wind': {'speed': 2.7, 'deg': 313, 'gust': 5.47},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-28 00:00:00'},
 {'dt': 1779937200,
  'main': {'temp': 10.69,
   'feels_like': 9.93,
   'temp_min': 10.69,
   'temp_max': 10.69,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 81,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 2.92, 'deg': 308, 'gust': 5.95},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 03:00:00'},
 {'dt': 1779948000,
  'main': {'temp': 14.42,
   'feels_like': 13.67,
   'temp_min': 14.42,
   'temp_max': 14.42,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 67,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 7},
  'wind': {'speed': 3.03, 'deg': 302, 'gust': 4.23},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 06:00:00'},
 {'dt': 1779958800,
  'main': {'temp': 18.84,
   'feels_like': 17.82,
   'temp_min': 18.84,
   'temp_max': 18.84,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 40,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 24},
  'wind': {'speed': 3.49, 'deg': 299, 'gust': 4.1},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 09:00:00'},
 {'dt': 1779969600,
  'main': {'temp': 21.63,
   'feels_like': 20.68,
   'temp_min': 21.63,
   'temp_max': 21.63,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 32,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 24},
  'wind': {'speed': 3.94, 'deg': 300, 'gust': 4.1},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 12:00:00'},
 {'dt': 1779980400,
  'main': {'temp': 20.9,
   'feels_like': 19.88,
   'temp_min': 20.9,
   'temp_max': 20.9,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1019,
   'humidity': 32,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 21},
  'wind': {'speed': 4.24, 'deg': 301, 'gust': 4.21},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 15:00:00'},
 {'dt': 1779991200,
  'main': {'temp': 18.41,
   'feels_like': 17.38,
   'temp_min': 18.41,
   'temp_max': 18.41,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1018,
   'humidity': 41,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 17},
  'wind': {'speed': 4.02, 'deg': 296, 'gust': 4.77},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-28 18:00:00'},
 {'dt': 1780002000,
  'main': {'temp': 14.5,
   'feels_like': 13.6,
   'temp_min': 14.5,
   'temp_max': 14.5,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1020,
   'humidity': 61,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 10},
  'wind': {'speed': 1.75, 'deg': 359, 'gust': 2.79},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-28 21:00:00'},
 {'dt': 1780012800,
  'main': {'temp': 13.36,
   'feels_like': 12.53,
   'temp_min': 13.36,
   'temp_max': 13.36,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 68,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 29},
  'wind': {'speed': 0.6, 'deg': 215, 'gust': 0.75},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-29 00:00:00'},
 {'dt': 1780023600,
  'main': {'temp': 12.06,
   'feels_like': 11.12,
   'temp_min': 12.06,
   'temp_max': 12.06,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 69,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 21},
  'wind': {'speed': 1.46, 'deg': 253, 'gust': 1.58},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 03:00:00'},
 {'dt': 1780034400,
  'main': {'temp': 15.67,
   'feels_like': 14.65,
   'temp_min': 15.67,
   'temp_max': 15.67,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 52,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 16},
  'wind': {'speed': 2.14, 'deg': 223, 'gust': 3.25},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 06:00:00'},
 {'dt': 1780045200,
  'main': {'temp': 21.07,
   'feels_like': 20.2,
   'temp_min': 21.07,
   'temp_max': 21.07,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1018,
   'humidity': 37,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 14},
  'wind': {'speed': 2.95, 'deg': 248, 'gust': 3.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 09:00:00'},
 {'dt': 1780056000,
  'main': {'temp': 24.8,
   'feels_like': 23.96,
   'temp_min': 24.8,
   'temp_max': 24.8,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1016,
   'humidity': 24,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 10},
  'wind': {'speed': 3.71, 'deg': 285, 'gust': 4.43},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 12:00:00'},
 {'dt': 1780066800,
  'main': {'temp': 25.55,
   'feels_like': 24.84,
   'temp_min': 25.55,
   'temp_max': 25.55,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 1015,
   'humidity': 26,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 4.07, 'deg': 294, 'gust': 5.35},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 15:00:00'},
 {'dt': 1780077600,
  'main': {'temp': 22.34,
   'feels_like': 21.78,
   'temp_min': 22.34,
   'temp_max': 22.34,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1015,
   'humidity': 44,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 38},
  'wind': {'speed': 2.87, 'deg': 321, 'gust': 5.85},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-29 18:00:00'},
 {'dt': 1780088400,
  'main': {'temp': 19.37,
   'feels_like': 19.09,
   'temp_min': 19.37,
   'temp_max': 19.37,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1013,
   'humidity': 66,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.86, 'deg': 242, 'gust': 4.87},
  'visibility': 10000,
  'pop': 0.51,
  'rain': {'3h': 0.25},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-29 21:00:00'},
 {'dt': 1780099200,
  'main': {'temp': 17.46,
   'feels_like': 17.56,
   'temp_min': 17.46,
   'temp_max': 17.46,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1012,
   'humidity': 88,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.75, 'deg': 288, 'gust': 8.79},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.61},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-30 00:00:00'},
 {'dt': 1780110000,
  'main': {'temp': 16.49,
   'feels_like': 16.6,
   'temp_min': 16.49,
   'temp_max': 16.49,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1011,
   'humidity': 92,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.32, 'deg': 285, 'gust': 9.32},
  'visibility': 10000,
  'pop': 0.93,
  'rain': {'3h': 0.41},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 03:00:00'},
 {'dt': 1780120800,
  'main': {'temp': 16.97,
   'feels_like': 16.79,
   'temp_min': 16.97,
   'temp_max': 16.97,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1011,
   'humidity': 79,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 86},
  'wind': {'speed': 5.24, 'deg': 304, 'gust': 8.01},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.37},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 06:00:00'},
 {'dt': 1780131600,
  'main': {'temp': 20.35,
   'feels_like': 19.72,
   'temp_min': 20.35,
   'temp_max': 20.35,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1011,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 3},
  'wind': {'speed': 5.49, 'deg': 310, 'gust': 7.25},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 09:00:00'},
 {'dt': 1780142400,
  'main': {'temp': 22.93,
   'feels_like': 22.32,
   'temp_min': 22.93,
   'temp_max': 22.93,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1011,
   'humidity': 40,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 2},
  'wind': {'speed': 5.87, 'deg': 307, 'gust': 7.55},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 12:00:00'},
 {'dt': 1780153200,
  'main': {'temp': 21.42,
   'feels_like': 20.98,
   'temp_min': 21.42,
   'temp_max': 21.42,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1010,
   'humidity': 52,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 20},
  'wind': {'speed': 6.23, 'deg': 302, 'gust': 7.21},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 15:00:00'},
 {'dt': 1780164000,
  'main': {'temp': 19.19,
   'feels_like': 18.78,
   'temp_min': 19.19,
   'temp_max': 19.19,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 62,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 57},
  'wind': {'speed': 4.26, 'deg': 308, 'gust': 6.44},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-30 18:00:00'},
 {'dt': 1780174800,
  'main': {'temp': 16.15,
   'feels_like': 16.01,
   'temp_min': 16.15,
   'temp_max': 16.15,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1010,
   'humidity': 84,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 75},
  'wind': {'speed': 2.53, 'deg': 317, 'gust': 5.46},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-30 21:00:00'},
 {'dt': 1780185600,
  'main': {'temp': 14.46,
   'feels_like': 14.29,
   'temp_min': 14.46,
   'temp_max': 14.46,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1010,
   'humidity': 89,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 53},
  'wind': {'speed': 2.23, 'deg': 291, 'gust': 4.74},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-31 00:00:00'},
 {'dt': 1780196400,
  'main': {'temp': 12.94,
   'feels_like': 12.64,
   'temp_min': 12.94,
   'temp_max': 12.94,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1009,
   'humidity': 90,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 28},
  'wind': {'speed': 2.2, 'deg': 293, 'gust': 4.3},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 03:00:00'},
 {'dt': 1780207200,
  'main': {'temp': 15.09,
   'feels_like': 14.59,
   'temp_min': 15.09,
   'temp_max': 15.09,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1009,
   'humidity': 74,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 61},
  'wind': {'speed': 2.83, 'deg': 283, 'gust': 4.24},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 06:00:00'},
 {'dt': 1780218000,
  'main': {'temp': 20.41,
   'feels_like': 19.73,
   'temp_min': 20.41,
   'temp_max': 20.41,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1007,
   'humidity': 47,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 60},
  'wind': {'speed': 2.33, 'deg': 281, 'gust': 2.82},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 09:00:00'},
 {'dt': 1780228800,
  'main': {'temp': 23.6,
   'feels_like': 23.01,
   'temp_min': 23.6,
   'temp_max': 23.6,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1006,
   'humidity': 38,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 70},
  'wind': {'speed': 3.21, 'deg': 277, 'gust': 3.9},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 12:00:00'},
 {'dt': 1780239600,
  'main': {'temp': 24.34,
   'feels_like': 23.8,
   'temp_min': 24.34,
   'temp_max': 24.34,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1005,
   'humidity': 37,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 61},
  'wind': {'speed': 3.52, 'deg': 307, 'gust': 4.08},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 15:00:00'},
 {'dt': 1780250400,
  'main': {'temp': 20.82,
   'feels_like': 20.29,
   'temp_min': 20.82,
   'temp_max': 20.82,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 51,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 80},
  'wind': {'speed': 2.86, 'deg': 333, 'gust': 4.54},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-31 18:00:00'},
 {'dt': 1780261200,
  'main': {'temp': 19.02,
   'feels_like': 18.49,
   'temp_min': 19.02,
   'temp_max': 19.02,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 1.31, 'deg': 320, 'gust': 1.97},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-31 21:00:00'},
 {'dt': 1780272000,
  'main': {'temp': 16.32,
   'feels_like': 15.86,
   'temp_min': 16.32,
   'temp_max': 16.32,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 71,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.25, 'deg': 278, 'gust': 3.59},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-06-01 00:00:00'},
 {'dt': 1780282800,
  'main': {'temp': 14.89,
   'feels_like': 14.6,
   'temp_min': 14.89,
   'temp_max': 14.89,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1004,
   'humidity': 83,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.88, 'deg': 261, 'gust': 7.43},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 03:00:00'},
 {'dt': 1780293600,
  'main': {'temp': 14.43,
   'feels_like': 14.17,
   'temp_min': 14.43,
   'temp_max': 14.43,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1006,
   'humidity': 86,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.46, 'deg': 282, 'gust': 10.32},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 06:00:00'},
 {'dt': 1780304400,
  'main': {'temp': 19.12,
   'feels_like': 18.5,
   'temp_min': 19.12,
   'temp_max': 19.12,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1006,
   'humidity': 54,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 96},
  'wind': {'speed': 5.21, 'deg': 284, 'gust': 7.3},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 09:00:00'},
 {'dt': 1780315200,
  'main': {'temp': 22.41,
   'feels_like': 21.72,
   'temp_min': 22.41,
   'temp_max': 22.41,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1005,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 85},
  'wind': {'speed': 4.91, 'deg': 274, 'gust': 6.95},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 12:00:00'},
 {'dt': 1780326000,
  'main': {'temp': 19.15,
   'feels_like': 18.64,
   'temp_min': 19.15,
   'temp_max': 19.15,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1005,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 91},
  'wind': {'speed': 5.12, 'deg': 270, 'gust': 7.34},
  'visibility': 10000,
  'pop': 0.34,
  'rain': {'3h': 0.12},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 15:00:00'},
 {'dt': 1780336800,
  'main': {'temp': 17.32,
   'feels_like': 17.01,
   'temp_min': 17.32,
   'temp_max': 17.32,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1005,
   'humidity': 73,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 95},
  'wind': {'speed': 3.66, 'deg': 278, 'gust': 8.08},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.93},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-06-01 18:00:00'}]

Looks like the information we'll want is in `list`. Let's look at the first element of `list` to investigate further.

In [8]:
json["list"][0]

{'dt': 1779915600,
 'main': {'temp': 16.54,
  'feels_like': 15.42,
  'temp_min': 15.01,
  'temp_max': 16.54,
  'pressure': 1023,
  'sea_level': 1023,
  'grnd_level': 1019,
  'humidity': 45,
  'temp_kf': 1.53},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'clouds': {'all': 4},
 'wind': {'speed': 2.94, 'deg': 331, 'gust': 6.35},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'n'},
 'dt_txt': '2026-05-27 21:00:00'}

In [9]:
json["city"]

{'id': 6545310,
 'name': 'Mitte',
 'coord': {'lat': 52.52, 'lon': 13.405},
 'country': 'DE',
 'population': 329078,
 'timezone': 7200,
 'sunrise': 1779850484,
 'sunset': 1779909158}

# Building a DataFrame

## What would we like from the json?
Let's begin by exploring the first 2 items of `list` and see what we have.

In [10]:
json["list"][0]

{'dt': 1779915600,
 'main': {'temp': 16.54,
  'feels_like': 15.42,
  'temp_min': 15.01,
  'temp_max': 16.54,
  'pressure': 1023,
  'sea_level': 1023,
  'grnd_level': 1019,
  'humidity': 45,
  'temp_kf': 1.53},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'clouds': {'all': 4},
 'wind': {'speed': 2.94, 'deg': 331, 'gust': 6.35},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'n'},
 'dt_txt': '2026-05-27 21:00:00'}

In [11]:
json["list"][1]

{'dt': 1779926400,
 'main': {'temp': 14.67,
  'feels_like': 13.76,
  'temp_min': 13.35,
  'temp_max': 14.67,
  'pressure': 1023,
  'sea_level': 1023,
  'grnd_level': 1019,
  'humidity': 60,
  'temp_kf': 1.32},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01n'}],
 'clouds': {'all': 7},
 'wind': {'speed': 2.7, 'deg': 313, 'gust': 5.47},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'n'},
 'dt_txt': '2026-05-28 00:00:00'}

When deciding what is useful, remember the project goals.

The time the forecast is for will be useful.

In [12]:
json["list"][0]["dt_txt"]

'2026-05-27 21:00:00'

The temperature will be useful. Scooters don't have heaters!

In [14]:
json["list"][0]["main"]["temp"]

16.54

The forecast will be useful. Scooters don't have a roof!

In [15]:
json["list"][0]["weather"][0]["main"]

'Clear'

If it's been recently raining will be useful. Wet conditions will affect scooter rentals.

In [15]:
json["list"][0]["rain"]["3h"]

KeyError: 'rain'

> If you get an error on 'rain', it's because it hasn't rained in the last 3 hours. But we know this key exists, because we read the [docs](https://openweathermap.org/forecast5)

Wind speed will be useful. It's likely to affect whether people rent scooters or not.

In [16]:
json["list"][0]["wind"]["speed"]

2.94

## Bringing together our chosen items

In [17]:
weather_items = []

for item in json["list"]:
    weather_item = {
        "forecast_time": item.get("dt_txt", None),
        "temperature": item["main"].get("temp", None),
        "forecast": item["weather"][0].get("main", None),
        "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
        "wind_speed": item["wind"].get("speed", None),
    }

    weather_items.append(weather_item)

weather_df = pd.DataFrame(weather_items)

weather_df.head()

         forecast_time  temperature forecast  rain_in_last_3h  wind_speed
0  2026-05-27 21:00:00        16.54    Clear              0.0        2.94
1  2026-05-28 00:00:00        14.67    Clear              0.0        2.70
2  2026-05-28 03:00:00        10.69    Clear              0.0        2.92
3  2026-05-28 06:00:00        14.42    Clear              0.0        3.03
4  2026-05-28 09:00:00        18.84   Clouds              0.0        3.49

The `rain` key in the JSON data is not always present. In the absence of this key, it's assumed that there hasn't been any recent rainfall. Since this key isn't always available, not encountering it during our loop can cause an error. To address this, we'll employ two `.get()` methods to handle the absence of the `rain` key.

> **Remember:** The second parameter of `.get()` serves as a fallback value, which is inserted into our dictionary if the key we're looking for doesn't exist.

The first `.get()` method checks for the existence of the `rain` key. If present, it will use the value associated with that key. If the `rain` key is missing, an empty dictionary will be used, preventing the code from breaking. The second `.get()` method checks for the `3h` key. If present, it will use its value. Otherwise, a default value of `0` will be used.

# Creating a function for multiple cities

In [18]:
import pandas as pd
from datetime import datetime
from pytz import timezone
import os
from dotenv import load_dotenv

def fetch_weather_data(cities):
  # Let's ensure the timezone is our local timezone
  berlin_timezone = timezone('Europe/Berlin')
  load_dotenv()
  API_key = os.getenv("openWeatherApi")
  weather_items = []

  for city in cities:

    country = "DE"

    # Geocoder api to get the latitude and longitude
    # This information should be from your SQL table, but we don't have that here
    geo_url = (f"http://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=5&appid={API_key}")
    geo_response = requests.get(geo_url)
    geo_json = geo_response.json()
    latitude = geo_json[0]["lat"]
    longitude = geo_json[0]["lon"]

    # weather api
    weather_url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")
    weather_response = requests.get(weather_url)
    weather_json = weather_response.json()

    # Added the time retrieved so we know when the forecast was made
    retrieval_time = datetime.now(berlin_timezone).strftime("%Y-%m-%d %H:%M:%S")

    for item in weather_json["list"]:
        weather_item = {
            # Added the city name, so the information is clear when looking at multiple cities
            "city": city,
            "forecast_time": item.get("dt_txt", None),
            "temperature": item["main"].get("temp", None),
            "forecast": item["weather"][0].get("main", None),
            "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
            "wind_speed": item["wind"].get("speed", None),
            "data_retrieved_at": retrieval_time
        }

        weather_items.append(weather_item)

  weather_df = pd.DataFrame(weather_items)

  return weather_df

In [19]:
fetch_weather_data(["Berlin", "Hamburg", "Munich"])

,city,forecast_time,temperature,forecast,rain_in_last_3h,wind_speed,data_retrieved_at
0,Berlin,2026-05-27 21:00:00,16.38,Clear,0.00,2.94,2026-05-27 21:22:46
1,Berlin,2026-05-28 00:00:00,14.59,Clear,0.00,2.70,2026-05-27 21:22:46
2,Berlin,2026-05-28 03:00:00,10.69,Clear,0.00,2.92,2026-05-27 21:22:46
3,Berlin,2026-05-28 06:00:00,14.42,Clear,0.00,3.03,2026-05-27 21:22:46
4,Berlin,2026-05-28 09:00:00,18.84,Clouds,0.00,3.49,2026-05-27 21:22:46
...,...,...,...,...,...,...,...
115,Munich,2026-06-01 06:00:00,13.93,Rain,0.69,3.78,2026-05-27 21:22:46
116,Munich,2026-06-01 09:00:00,18.20,Clouds,0.00,3.75,2026-05-27 21:22:46
117,Munich,2026-06-01 12:00:00,19.46,Clouds,0.00,4.03,2026-05-27 21:22:46
118,Munich,2026-06-01 15:00:00,20.88,Clouds,0.00,3.69,2026-05-27 21:22:46
119,Munich,2026-06-01 18:00:00,17.92,Clouds,0.00,0.23,2026-05-27 21:22:46

# Making our function work with our SQL cities data
This section delves into a more advanced aspect of the project, which may be beyond the point many of you got to. However, it serves as an illustrative example of how to structure your work effectively. It demonstrates how we can compartmentalise various aspects of our data processing pipeline into distinct functions, enhancing code readability and facilitating debugging.
> This part will only work locally, not on colab. You must also create your weather table in SQL first.

```sql
-- Create the 'weather' table
CREATE TABLE weather (
    city_id INT NOT NULL,
    forecast_time DATETIME NOT NULL,
    temperature FLOAT,
    forecast VARCHAR(255),
    rain_in_last_3h FLOAT,
    wind_speed FLOAT,
    data_retrieved_at DATETIME NOT NULL,

    PRIMARY KEY (city_id, forecast_time),

    FOREIGN KEY (city_id)
        REFERENCES cities(city_id)
);
```

In [20]:
import pandas as pd
import requests
from pytz import timezone
from datetime import datetime
import os
from dotenv import load_dotenv

def retrieve_and_send_data():

  def _create_connection_string():
    schema = "gans_db"
    host = "127.0.0.1"
    user = "root"
    password = os.getenv("MYSQL_PASSWORD")
    port = 3306
    return f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

  def _fetch_cities_data(connection_string):
    return pd.read_sql("cities", con=connection_string)

  def _fetch_weather_data(cities_df):
    berlin_timezone = timezone('Europe/Berlin')
    API_key = os.getenv("openWeatherApi")
    weather_items = []

    for _, city in cities_df.iterrows():
        latitude = city["latitude"]
        longitude = city["longitude"]
        city_id = city["city_id"]

        url = (f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}&units=metric")
        response = requests.get(url)
        weather_data = response.json()

        retrieval_time = datetime.now(berlin_timezone).strftime("%Y-%m-%d %H:%M:%S")

        for item in weather_data["list"]:
            weather_item = {
                "city_id": city_id,
                "forecast_time": item.get("dt_txt"),
                "temperature": item["main"].get("temp"),
                "forecast": item["weather"][0].get("main"),
                "rain_in_last_3h": item.get("rain", {}).get("3h", 0),
                "wind_speed": item["wind"].get("speed"),
                "data_retrieved_at": retrieval_time
            }
            weather_items.append(weather_item)

    weather_df = pd.DataFrame(weather_items)
    weather_df["forecast_time"] = pd.to_datetime(weather_df["forecast_time"])
    weather_df["data_retrieved_at"] = pd.to_datetime(weather_df["data_retrieved_at"])

    return weather_df

  def _store_weather_data(weather_df, connection_string):
    weather_df.to_sql('weather',
                      if_exists='append',
                      con=connection_string,
                      index=False)

  load_dotenv()
  connection_string = _create_connection_string()
  cities_df = _fetch_cities_data(connection_string)
  weather_df = _fetch_weather_data(cities_df)
  _store_weather_data(weather_df, connection_string)
  return "Data has been updated"

In [21]:
retrieve_and_send_data()

'Data has been updated'